import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Regsiter",
  description: "Generated by create next app",
};

export default function Register() {
  return <div>Register</div>;
}
